networks:
  ghostfolio-local:

name: homeport-ghostfolio-local

services:
  ghostfolio-data-importer:
    build:
      context: ../..
      dockerfile: ./docker/node/Dockerfile
      args:
        - APP=ghostfolio
        - TAG=base-latest
    container_name: ghostfolio-importer-local
    env_file:
      - ./.env.local
    ports:
      - '3334:3001'
    networks:
      - ghostfolio-local
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  ghostfolio:
    build:
      context: ../..
      dockerfile: ./apps/ghostfolio/docker/ghostfolio.Dockerfile
    env_file:
      - ./.env.local
    depends_on:
      - ghostfolio-redis
      - ghostfolio-database
    container_name: ghostfolio-app-local
    ports:
      - 3333:3333
    restart: always
    networks:
      - ghostfolio-local
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  ghostfolio-database:
    build:
      context: ../..
      dockerfile: docker/postgres/Dockerfile
    depends_on:
      - ghostfolio-redis
    container_name: ghostfolio-db-local
    env_file:
      - ./.env.local
    restart: always
    networks:
      - ghostfolio-local
    volumes:
      - './local_data:/var/lib/postgresql/data'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  ghostfolio-redis:
    build:
      context: ../..
      dockerfile: ./apps/ghostfolio/docker/redis.Dockerfile
    container_name: ghostfolio-redis-local
    env_file:
      - ./.env.local
    restart: always
    networks:
      - ghostfolio-local
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    volumes:
      - './redis_data:/data'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
